language: csharp
solution: ./OperatorsAndCasts/OperatorsAndCasts/OperatorsAndCasts.sln
os:
  - linux
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libssl-dev
    - zlib1g
    - libstdc++6
install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - cd
  - mkdir dn_cli
  - cd dn_cli
  - wget http://launchpadlibrarian.net/217261845/libicu52_52.1-8ubuntu0.2_amd64.deb
  - sudo dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-host-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sdk-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sdk-ubuntu-x64.latest.deb