language: generic
sudo: required
dist: xenial

addons:
  apt:
    packages:
    - gettext
    - libunwind8
    - libicu52
    - dbus

before_install:
  - export DOTNET_INSTALL_DIR="~/cli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --install-dir ~/cli
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - dotnet --info
  - cd OperatorsAndCasts/OperatorsAndCasts/CastingSample
  - pwd
  - dotnet restore
  - dotnet run